language: ruby
before_script:
  - mysql -e 'create database ebisu_connection_test;'
  - mysql -e 'create database ebisu_connection_test_master;'
  - mysql -e 'create database ebisu_connection_test_slave;'
  - "bundle exec ruby spec/prepare.rb"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
notifications:
  emails:
    - tsukasa.oishi@gmail.com
