language: ruby
before_install:
  - gem install bundler
services:
  - mysql
  - postgresql
before_script:
  - bundle update
  - cp test/config/database_postgresql.yml.travis test/config/database_postgresql.yml
  - psql -c 'create database fresh_connection_test_master;' -U postgres
  - psql -c 'create database fresh_connection_test_slave1;' -U postgres
  - psql -c 'create database fresh_connection_test_slave2;' -U postgres
cache: bundler
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
gemfile:
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
matrix:
  exclude:
    - rvm: 2.3.0
      gemfile: gemfiles/rails40.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails40.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rails50.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails50.gemfile
  fast_finish: true
notifications:
  emails:
    - tsukasa.oishi@gmail.com
bundler_args: --jobs 3 --retry 3
