language: ruby
before_install:
  - gem install bundler
services:
  - mysql
  - postgresql
before_script:
  - bundle update
  - cp test/config/database_postgresql.yml.travis test/config/database_postgresql.yml
  - psql -c 'create database ebisu_connection_test_master;' -U postgres
  - psql -c 'create database ebisu_connection_test_replica;' -U postgres
cache: bundler
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
matrix:
  fast_finish: true
bundler_args: --jobs 3 --retry 3
